FcRoomBooking/Controllers/UserController.cs
using FcRoomBooking.Areas.Identity.Data;
using FcRoomBooking.Constants;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FcRoomBooking.Controllers
{
    //[Authorize]
    [Authorize(Permissions.User.View)]
    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        public UserController(UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            var currentUser = await _userManager.GetUserAsync(HttpContext.User);
            var allUsersExceptCurrentUser = await _userManager.Users.Where(a => a.Id != currentUser.Id).ToListAsync();
            return View(allUsersExceptCurrentUser);
        }
        [HttpGet, Authorize(Permissions.User.Edit)]
        public async Task<IActionResult> Edit(string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);
            return View(user);
        }
        [HttpPost, Authorize(Permissions.User.Edit)]
        public async Task<IActionResult> Edit(ApplicationUser model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByIdAsync(model.Id);
                user.Name = model.Name;
                user.Email = model.Email;
                user.UserName = model.Email;
                await _userManager.UpdateAsync(user);
                TempData["isUpdated"] = true;
                return RedirectToAction("Index");
            }
            return NotFound();
        }
        [HttpPost, Authorize(Permissions.User.Delete)]
        public async Task<IActionResult> Delete(ApplicationUser model)
        {
            var user = await _userManager.FindByIdAsync(model.Id);
            await _userManager.DeleteAsync(user);
            TempData["notAvailable"] = true;
            return RedirectToAction("Index");
            
        }
    }
}

FcRoomBooking/Controllers/UserRolesController.cs
using FcRoomBooking.Areas.Identity.Data;
using FcRoomBooking.Models.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FcRoomBooking.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserRolesController : Controller
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<ApplicationRole> _roleManager;
        public UserRolesController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, RoleManager<ApplicationRole> roleManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
        }
        public async Task<IActionResult> Index(string userId)
        {
            var viewModel = new List<UserRolesViewModel>();
            var user = await _userManager.FindByIdAsync(userId);
            foreach (var role in _roleManager.Roles.ToList())
            {
                var userRolesViewModel = new UserRolesViewModel
                {
                    RoleName = role.Name
                };
                if (await _userManager.IsInRoleAsync(user, role.Name))
                {
                    userRolesViewModel.Selected = true;
                }
                else
                {
                    userRolesViewModel.Selected = false;
                }
                viewModel.Add(userRolesViewModel);
            }
            var model = new ManageUserRolesViewModel()
            {
                UserId = userId,
                Email = user.Email,
                UserRoles = viewModel
            };
            return View(model);
        }
        public async Task<IActionResult> Update(string id, ManageUserRolesViewModel model)
        {
            var user = await _userManager.FindByIdAsync(id);
            var roles = await _userManager.GetRolesAsync(user);
            var result = await _userManager.RemoveFromRolesAsync(user, roles);
            result = await _userManager.AddToRolesAsync(user, model.UserRoles.Where(x => x.Selected).Select(y => y.RoleName));
            var currentUser = await _userManager.GetUserAsync(User);
            await _signInManager.RefreshSignInAsync(currentUser);
            //await Seeds.DefaultUsers.SeedSuperAdminAsync(_userManager, _roleManager);
            return RedirectToAction("Index", "User");
            //return RedirectToAction("Index", new { userId = id });
        }
    }
}

FcRoomBooking/Views/User/Edit.cshtml
@using FcRoomBooking.Constants
@using Microsoft.AspNetCore.Identity;
@inject IAuthorizationService AuthorizationService
@using Microsoft.AspNetCore.Authorization
@model FcRoomBooking.Areas.Identity.Data.ApplicationUser
@{
    Layout = "_LayoutAdmin";
}
 <div class="col-lg-12 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                        <form id="registerForm" enctype="multipart/form-data" method="post" asp-controller="User" asp-controller="Edit">
                            <input type="hidden" asp-for="Id" class="form-control" />
                                        <div class="col-lg-6">
                                        <h2>Edit User Account</h2>
                                        <hr />
                                        <div class="form-floating">
                                            <label asp-for="Email"></label>
                                            <input asp-for="Email" class="form-control" />
                                            
                                            <span asp-validation-for="Email" class="text-danger"></span>
                                        </div>
                                        <div class="form-floating">
                                            <label asp-for="Name"></label>
                                            <input asp-for="Name" class="form-control" />
                                            
                                            <span asp-validation-for="Name" class="text-danger"></span>
                                        </div>
                                        </div>
                                        <br />
                                        <button type="submit" class="btn btn-md btn-primary">Update</button>
                                        @if ((AuthorizationService.AuthorizeAsync(User, Permissions.User.Delete)).Result.Succeeded)
                                        {
                                               <button type="submit" class="btn btn-md btn-danger" asp-action="Delete" asp-controller="User">Delete</button>
                                        }
                    
                                        <a class="btn btn-secondary" asp-action="Index" asp-controller="User">Cancle</a>
                                        
                                

                       </form>
                <div class="cart-footer">
            </div>
 </div>
 @section Scripts {
    <partial name="_ValidationScriptsPartial" />      
}

FcRoomBooking/Views/User/Index.cshtml
@using FcRoomBooking.Constants
@using Microsoft.AspNetCore.Identity;
@inject IAuthorizationService AuthorizationService
@using Microsoft.AspNetCore.Authorization
@{
    Layout = "_LayoutAdmin";
}
@*@model IEnumerable<IdentityUser>*@
@model List<FcRoomBooking.Areas.Identity.Data.ApplicationUser>
<div class="col-12 grid-margin mb-1 stretch-card">
              <div class="card">
                <div class="card-body">
                    <div class="row pt-4">
                        <div class="col-6">
                            <h2 class="card-title">User List</h2>
                        </div>  
                        <div class="col-6 text-right" >
                            @if ((AuthorizationService.AuthorizeAsync(User, Permissions.User.Create)).Result.Succeeded)
                             {
                            <a class="nav-link" asp-area="Identity" asp-page="/Account/Register">Create User</a>
                             }
                        </div>
                    </div>
                </div>
            </div>
</div>

<div class="col-lg-12 d-flex flex-column grid-margin stretch-card bg-white p-4 rounded relative">
    <div class="table-responsive pt-3">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>
                        #
                    </th>
                    <th>
                        Profile
                    </th>
                    <th>
                        UserName
                    </th>
                    <th>
                        Email
                    </th>
                    <th>
                        Action
                    </th>     
                </tr>
            </thead>
            <tbody>
                @{
                    int no = 1;
                }
                @foreach (var user in Model)
                {
                    <tr>
                        <td>
                            @no
                        </td>
                        <td>
                            <a>
                                @if(user.ProfileImage != null)
                                {
                                    <img src="data:image/*;base64,@(Convert.ToBase64String(user.ProfileImage))">
                                }
                                else
                                {
                                    <img src="https://cdn-icons-png.flaticon.com/512/456/456212.png">
                                }

                                
                            </a>
                        </td>
                        <td>
                            <div class="row">
                                <div class="col-sm">
                                    <a>
                                        @user.UserName
                                    </a>
                                    <br>
                                    <small>
                                        @user.Id
                                    </small>
                                </div>
                            </div>
                        </td>
                        <td>
                            <a>
                                @user.Email
                            </a>
                        </td>
                        <td>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Action
                                </button>
                                <div class="dropdown-menu shadow animated--grow-in">
                                    <a style='margin-right:16px' asp-controller="UserRoles" asp-action="Index" asp-route-userId="@user.Id" class="dropdown-item">
                                        <i class="fas fa-wrench"></i> Manage Roles
                                    </a>
                                    @if ((AuthorizationService.AuthorizeAsync(User, Permissions.User.Edit)).Result.Succeeded)
                                    {
                                        <a style='margin-right:16px' asp-controller="User" asp-action="Edit" asp-route-userId="@user.Id" class="dropdown-item">
                                        <i class="fas fa-wrench"></i> Edit
                                        </a>    
                                    }
                                    
                                </div>
                                    
                                
                                
                                
                                
                            </div>
                        </td>
                    </tr>
                    no++;
                }
            </tbody>
        </table>

    </div>
</div>
<partial name="_ChosenPartial" />
@{
    if (TempData["notAvailable"] != null)
    {
        <script>
            $.toast({
                text: "User has been deleted!", // Text that is to be shown in the toast
                heading: ' User Deleted', // Optional heading to be shown on the toast
                icon: 'error', // Type of toast icon
                showHideTransition: 'fade', // fade, slide or plain
                allowToastClose: true, // Boolean value true or false
                hideAfter: 3000, // false to make it sticky or number representing the miliseconds as time after which toast needs to be hidden
                stack: 5, // false if there should be only one toast at a time or a number representing the maximum number of toasts to be shown at a time
                position: 'top-center', // bottom-left or bottom-right or bottom-center or top-left or top-right or top-center or mid-center or an object representing the left, right, top, bottom values
                textAlign: 'left',  // Text alignment i.e. left, right or center
            });
        </script>
    }
    if (TempData["isUpdated"] != null)
    {
        <script>
            $.toast({
                text: "User has been Updated!", // Text that is to be shown in the toast
                heading: 'User Updated', // Optional heading to be shown on the toast
                icon: 'info', // Type of toast icon
                showHideTransition: 'fade', // fade, slide or plain
                allowToastClose: true, // Boolean value true or false
                hideAfter: 2000, // false to make it sticky or number representing the miliseconds as time after which toast needs to be hidden
                stack: 5, // false if there should be only one toast at a time or a number representing the maximum number of toasts to be shown at a time
                position: 'top-center', // bottom-left or bottom-right or bottom-center or top-left or top-right or top-center or mid-center or an object representing the left, right, top, bottom values
                textAlign: 'left',  // Text alignment i.e. left, right or center
                loader: true,  // Whether to show loader or not. True by default
                loaderBg: '#9EC600',  // Background color of the toast loader
            });
        </script>
    }
}