FcRoomBooking/Models/ViewModel/RoleViewModel.cs
using FcRoomBooking.Areas.Identity.Data;
using Microsoft.AspNetCore.Identity;

namespace FcRoomBooking.Models.ViewModel
{
    public class RoleViewModel
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public List<ApplicationRole> Roles { get; set; }
        
    }
}

FcRoomBooking/Controllers/PermissionController.cs
using FcRoomBooking.Areas.Identity.Data;
using FcRoomBooking.Constants;
using FcRoomBooking.Helpers;
using FcRoomBooking.Models.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FcRoomBooking.Controllers
{
    [Authorize(Roles = "Admin")]
    public class PermissionController : Controller
    {
        private readonly RoleManager<ApplicationRole> _roleManager;

        public PermissionController(RoleManager<ApplicationRole> roleManager)
        {
            _roleManager = roleManager;
        }
        public async Task<ActionResult> Index(string roleId)
        {
            var model = new PermissionViewModel();
            var allPermissions = new List<RoleClaimsViewModel>();
            allPermissions.GetPermissions(typeof(Permissions.Booking), roleId);
            allPermissions.GetPermissions(typeof(Permissions.Room), roleId);
            allPermissions.GetPermissions(typeof(Permissions.User), roleId);
            var role = await _roleManager.FindByIdAsync(roleId);
            model.RoleId = roleId;
            var claims = await _roleManager.GetClaimsAsync(role);
            var allClaimValues = allPermissions.Select(a => a.Value).ToList();
            var roleClaimValues = claims.Select(a => a.Value).ToList();
            var authorizedClaims = allClaimValues.Intersect(roleClaimValues).ToList();
            foreach (var permission in allPermissions)
            {
                if (authorizedClaims.Any(a => a == permission.Value))
                {
                    permission.Selected = true;
                }
            }
            model.RoleClaims = allPermissions;
            return View(model);
        }
        public async Task<IActionResult> Update(PermissionViewModel model)
        {
            var role = await _roleManager.FindByIdAsync(model.RoleId);
            var claims = await _roleManager.GetClaimsAsync(role);
            foreach (var claim in claims)
            {
                await _roleManager.RemoveClaimAsync(role, claim);
            }
            var selectedClaims = model.RoleClaims.Where(a => a.Selected).ToList();
            foreach (var claim in selectedClaims)
            {
                await _roleManager.AddPermissionClaim(role, claim.Value);
            }
            return RedirectToAction("Index", "Role");
            //return RedirectToAction("Index", new { roleId = model.RoleId });
        }
    }
}

FcRoomBooking/Controllers/RoleController.cs
using FcRoomBooking.Areas.Identity.Data;
using FcRoomBooking.Models.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FcRoomBooking.Controllers
{
    [Authorize(Roles="Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<ApplicationRole> _roleManager;
        public RoleController(RoleManager<ApplicationRole> roleManager)
        {
            _roleManager = roleManager;
        }
        public async Task<IActionResult> Index()
        {
            var role = new RoleViewModel();
            role.Roles = await _roleManager.Roles.ToListAsync();
            ViewBag.type = TempData["type"];
            ViewBag.Message = TempData["Message"];
            return View(role);
        }
        [HttpPost]
        public async Task<IActionResult> AddRole(string roleName)
        {
            if (roleName != null)
            {
                await _roleManager.CreateAsync(new ApplicationRole(roleName.Trim()));
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> EditRole(string roleid)
        {

            var rolename = await _roleManager.Roles.FirstOrDefaultAsync(x => x.Id == roleid);
            RoleViewModel role = new RoleViewModel();
            role.Id = rolename.Id;
            role.Name = rolename.Name;
            return View(role);
        }
        [HttpPost]
        public async Task<IActionResult> EditRole(ApplicationRole model)
        {
            ApplicationRole role = await _roleManager.Roles.FirstOrDefaultAsync(x => x.Id == model.Id);
            role.Name = model.Name;
            await _roleManager.UpdateAsync(role); 
            TempData["type"] = "info";
            TempData["Message"] = "The role you selected has been updated successfully!";

            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> DeleteRole(string id)
        {
            var roleRemove = await _roleManager.Roles.Where(x=>x.Islocked !=true).FirstOrDefaultAsync(x => x.Id == id);
            RoleViewModel role = new RoleViewModel();
            if(roleRemove != null)
            {
                await _roleManager.DeleteAsync(roleRemove);
                TempData["type"] = "success";
                TempData["Message"] = "The role you selected has been deleted successfully!";
            }
            else
            {
                TempData["type"] = "danger";
                TempData["Message"] = "The role you selected can not be deleted!";
            }
            
            return RedirectToAction("Index");
        }


    }
}

FcRoomBooking/Views/Role/EditRole.cshtml
@model FcRoomBooking.Models.ViewModel.RoleViewModel
@using Microsoft.AspNetCore.Identity;
@{
    Layout = "_LayoutAdmin";
}
<div class="col-lg-12 d-flex flex-column grid-margin stretch-card bg-white p-4 rounded shadow-sm">
    <div class="card-body">
        <h4 class="card-title mb-5">Edit Role</h4>
        <form class="forms-sample" method="post" asp-controller="Role" asp-action="EditRole">
            <div class="form-group row">
               
                <input type="hidden" class="form-control" id="exampleInputUsername1" asp-for="Id" >
                
                <div class="col-md-6">
                    <label for="exampleInputUsername1">Role Name</label>
                    <input type="text" class="form-control" id="exampleInputUsername1" asp-for="Name" >
                </div>
                
            </div>
            
            <button type="submit" class="btn btn-primary mr-2">Save</button>
            
            @*<button type="submit" asp-controller="Role" asp-action="DeleteRole" asp-route-id="@Model.Id" class="btn btn-danger">Delete</button>*@
            <a type="submit" data-bs-toggle="modal" data-bs-target="#RoleModal" class="btn btn-danger">Delete</a>
            <a class="btn btn-light" asp-controller="Role" asp-action="index">Cancel</a>
        </form>
    </div>
</div>
<partial name="_DeletePartialView"></partial>

FcRoomBooking/Views/Role/Index.cshtml
@using Microsoft.AspNetCore.Identity;
@*@public IEnumerable<IdentityRole>*@
@model FcRoomBooking.Models.ViewModel.RoleViewModel
<div id="modalWrapper">
    @*@inject RoleManager<ApplicationRole> RoleManager*@
</div>
@{
    Layout = "_LayoutAdmin";
}


<div class="col-lg-12 grid-margin stretch-card">
              <div class="card">
                  <partial name="_MessagePartail"></partial>
                <div class="card-body">
                  <h4 class="card-title">Role</h4>
                  <div class="table-responsive">
                      <form method="post" asp-action="AddRole" asp-controller="Role">
                            <div class="input-group">
                                <input name="roleName" class="form-control w-25">
                                <span class="input-group-btn">
                                    <button class="btn btn-info">Add New Role</button>
                                </span>
                            </div>
                        </form>
                    <table class="table table-striped">
                      <thead>
                        <tr>
                          <th>
                                Role
                            </th>
                            <th>
                                Id
                            </th>
                            <th style="width:10%">
                                Actions
                            </th>
                        </tr>
                      </thead>
                      <tbody>
                        @foreach (var role in Model.Roles)
                            {
                                <tr>
                                    <td>
                                        @role.Name
                                    </td>
                                    <td>
                                        @role.Id
                                    </td>
                                    <td class="text-right">
                                        <div class="btn-group">
                                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                Action
                                            </button>
                                            <div class="dropdown-menu shadow animated--grow-in">
                                                <a class="dropdown-item" asp-controller="Role" asp-action="EditRole" asp-route-roleid="@role.Id">
                                                    <i class="fas fa-pencil-alt"></i> Edit
                                                </a>
                                                 
                                                <form class="d-inline">
                                                    @*<a class="dropdown-item" data-bs-toggle="modal" data-bs-target="#RoleModal" data-url="@Url.Action($"GetRole/{role.Id}")">
                                                        <i class="fas fa-trash-alt"></i> Delete</a>*@
                                                    @*<a id="deleteItem" class="dropdown-item" data-target="#basic" data-toggle="modal" 
                                                        data-path="@Url.Action("DeleteRole", "Role", new { id = @Model.Id })">Delete</a>*@
                                                    
                                                    
                                                     
                                                   
                                                   
                                                </form>
                                                @if (role.Name != "Admin")
                                                {
                                                    <a style='margin-right:16px' asp-controller="Permission" asp-action="Index" asp-route-roleId="@role.Id" class="dropdown-item">
                                                        <i class="fas fa-wrench"></i> Manage Permissions
                                                    </a>
                                                }
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            }
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>

            




              
           
                
            
   
 

            