FcRoomBooking/Controllers/RoleController.cs
using FcRoomBooking.Areas.Identity.Data;
using FcRoomBooking.Models.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FcRoomBooking.Controllers
{
    [Authorize(Roles="Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<ApplicationRole> _roleManager;
        public RoleController(RoleManager<ApplicationRole> roleManager)
        {
            _roleManager = roleManager;
        }
        public async Task<IActionResult> Index()
        {
            var role = new RoleViewModel();
            role.Roles = await _roleManager.Roles.ToListAsync();
            ViewBag.type = TempData["type"];
            ViewBag.Message = TempData["Message"];
            return View(role);
        }
        [HttpPost]
        public async Task<IActionResult> AddRole(string roleName)
        {
            if (roleName != null)
            {
                await _roleManager.CreateAsync(new ApplicationRole(roleName.Trim()));
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> EditRole(string roleid)
        {

            var rolename = await _roleManager.Roles.FirstOrDefaultAsync(x => x.Id == roleid);
            RoleViewModel role = new RoleViewModel();
            role.Id = rolename.Id;
            role.Name = rolename.Name;
            return View(role);
        }
        [HttpPost]
        public async Task<IActionResult> EditRole(ApplicationRole model)
        {
            ApplicationRole role = await _roleManager.Roles.FirstOrDefaultAsync(x => x.Id == model.Id);
            role.Name = model.Name;
            await _roleManager.UpdateAsync(role); 
            TempData["type"] = "info";
            TempData["Message"] = "The role you selected has been updated successfully!";

            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> DeleteRole(string id)
        {
            var roleRemove = await _roleManager.Roles.Where(x=>x.Islocked !=true).FirstOrDefaultAsync(x => x.Id == id);
            RoleViewModel role = new RoleViewModel();
            if(roleRemove != null)
            {
                await _roleManager.DeleteAsync(roleRemove);
                TempData["type"] = "success";
                TempData["Message"] = "The role you selected has been deleted successfully!";
            }
            else
            {
                TempData["type"] = "danger";
                TempData["Message"] = "The role you selected can not be deleted!";
            }
            
            return RedirectToAction("Index");
        }


    }
}

FcRoomBooking/Controllers/RoomBookingController.cs
using FcRoomBooking.Areas.Identity.Data;
using FcRoomBooking.Models.Domain;
using FcRoomBooking.Models.ViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace FcRoomBooking.Controllers
{
    public class RoomBookingController : Controller
    {
        private readonly ApplicationDbContext dbContext;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly RoleManager<ApplicationRole> roleManager;

        public RoomBookingController(ApplicationDbContext dbContext, UserManager<ApplicationUser> userManager, RoleManager<ApplicationRole> roleManager)
        {
            this.dbContext = dbContext;
            this.userManager = userManager;
            this.roleManager = roleManager;
        }
        public IActionResult Index()
        {
            CheckBookingViewModel model = new CheckBookingViewModel();
            model.RoomBooking = dbContext.RoomBookings.OrderByDescending(x=>x.BookingTo).Include(x => x.Room).Include(x => x.ApplicationUser).Where(x => x.BookingStatus == "Active" || x.BookingStatus == "Ongoing").ToList();
            model.Participant = dbContext.Participants.ToList();
            return View(model);
        }
        [HttpGet("RoomBooking/{id}")]
        public IActionResult Index(int id)
        {
            CheckBookingViewModel model = new CheckBookingViewModel();
            model.RoomBooking = dbContext.RoomBookings.OrderByDescending(x => x.BookingTo).Include(x => x.Room).Include(x => x.ApplicationUser).Where(x => x.BookingStatus == "Active" || x.BookingStatus == "Ongoing").Where(x => x.Id == id).ToList();
            model.Participant = dbContext.Participants.ToList();
            return View(model);
        }
        public IActionResult Participant(int id)
        {
            var list = dbContext.Participants.Include(x => x.ApplicationUser).ToList().FindAll(x => x.RoomBookingId == id);
            var newlist = new List<ParticipantViewModel>();
            if (list.Any())
            {
                foreach (var item in list)
                {
                    newlist.Add(new ParticipantViewModel
                    {
                        RoomBookingId = id,
                        Username = item.ApplicationUser.Name,
                        Email = item.ApplicationUser.Email,
                        Reason = item.Reason,
                        IsExcept = item.IsExcept,
                        Id = item.Id,

                    });
                }
                ViewBag.BookingId = id;
            }
            return View(newlist);

        }
        [HttpGet]
        public IActionResult show(int Id)
        {
            var show = dbContext.Participants.FirstOrDefault(x => x.Id == Id);
            return PartialView("_ReasonPartialView", show);

        }
        [HttpGet]
        public IActionResult Responce(int id)
        {
            var user = userManager.GetUserId(User);
            ResponceViewModel view = new ResponceViewModel();
            view.RoomBooking = dbContext.RoomBookings.Include(x => x.ApplicationUser).Include(x => x.Room).FirstOrDefault(x => x.Id == id);
            view.Participant = dbContext.Participants.Where(x => x.RoomBookingId == id).Where(x => x.UserId == user.ToString()).FirstOrDefault();

            return View(view);
        }
        
        [HttpPost]
        public IActionResult Accept(ResponceViewModel model)
        {
            var participant = dbContext.Participants.Where(x=>x.UserId == model.Participant.UserId).FirstOrDefault(x=>x.RoomBookingId == model.RoomBooking.Id);
            if(model.Participant.IsExcept == true)
            {
                participant.IsExcept = model.Participant.IsExcept;
                participant.Reason = null;
                TempData["isJoin"] = true;
                

            }
            else if(model.Participant.IsExcept == false)
            {
                participant.IsExcept = model.Participant.IsExcept;
                participant.Reason = model.Participant.Reason;
                TempData["notAvailable"] = true;
            }
            dbContext.Participants.Update(participant);
            dbContext.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

FcRoomBooking/Controllers/RoomController.cs
using FcRoomBooking.Areas.Identity.Data;
using FcRoomBooking.Constants;
using FcRoomBooking.Models.Domain;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FcRoomBooking.Controllers
{
    public class RoomController : Controller
    {
        private readonly ApplicationDbContext _applicationDbContext;
        public RoomController(ApplicationDbContext applicationDbContext)
        {
            _applicationDbContext = applicationDbContext;
        }

        public IActionResult List()
        {
            var Room = _applicationDbContext.Rooms.ToList();
            return View(Room);
        }
        [Authorize(Permissions.Room.Create)]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost, Authorize(Permissions.Room.Create)]
        public async Task<IActionResult> Create(Room room, List<IFormFile> image)
        {
            if (ModelState.IsValid)
            {
                foreach (var item in image)
                {
                    if (item.Length > 0)
                    {
                        using (var stream = new MemoryStream())
                        {
                            await item.CopyToAsync(stream);
                            room.RoomImage = stream.ToArray();
                        }
                    }
                }

                await _applicationDbContext.Rooms.AddAsync(room);
                await _applicationDbContext.SaveChangesAsync();

                return RedirectToAction("Create");
            }
            return View(room);
        }
        [HttpGet, Authorize(Permissions.Room.Edit)]
        public async Task<IActionResult> Edit(int id)
        {
            var room = await _applicationDbContext.Rooms.FirstOrDefaultAsync(x => x.Id == id);
            return View(room);
        }
        [HttpPost, Authorize(Permissions.Room.Edit)]
        public async Task<IActionResult> Edit(Room model)
        {
            var room = await _applicationDbContext.Rooms.FirstOrDefaultAsync(x => x.Id == model.Id);
            if (model.image != null)
            {
                if (model.image.Length > 0)
                {
                    using (var stream = new MemoryStream())
                    {
                        await model.image.CopyToAsync(stream);
                        model.RoomImage = stream.ToArray();
                    }
                }
            }
            else
            {
                model.RoomImage = room?.RoomImage;
            }
            room.RoomImage = model.RoomImage;
            room.RoomName = model.RoomName;
            room.RoomDescription = model.RoomDescription;
            _applicationDbContext.Rooms.Update(room);
            await _applicationDbContext.SaveChangesAsync();
            return RedirectToAction("List");
        }
        [HttpPost, Authorize(Permissions.Room.Delete)]
        public async Task<IActionResult> Delete(Room model)
        {
            var room = await _applicationDbContext.Rooms.FindAsync(model.Id);
            _applicationDbContext.Rooms.Remove(room);
            await _applicationDbContext.SaveChangesAsync();
            return RedirectToAction("List");
        }
    }
}

FcRoomBooking/Controllers/UserController.cs
using FcRoomBooking.Areas.Identity.Data;
using FcRoomBooking.Constants;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FcRoomBooking.Controllers
{
    //[Authorize]
    [Authorize(Permissions.User.View)]
    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        public UserController(UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            var currentUser = await _userManager.GetUserAsync(HttpContext.User);
            var allUsersExceptCurrentUser = await _userManager.Users.Where(a => a.Id != currentUser.Id).ToListAsync();
            return View(allUsersExceptCurrentUser);
        }
        [HttpGet, Authorize(Permissions.User.Edit)]
        public async Task<IActionResult> Edit(string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);
            return View(user);
        }
        [HttpPost, Authorize(Permissions.User.Edit)]
        public async Task<IActionResult> Edit(ApplicationUser model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByIdAsync(model.Id);
                user.Name = model.Name;
                user.Email = model.Email;
                user.UserName = model.Email;
                await _userManager.UpdateAsync(user);
                TempData["isUpdated"] = true;
                return RedirectToAction("Index");
            }
            return NotFound();
        }
        [HttpPost, Authorize(Permissions.User.Delete)]
        public async Task<IActionResult> Delete(ApplicationUser model)
        {
            var user = await _userManager.FindByIdAsync(model.Id);
            await _userManager.DeleteAsync(user);
            TempData["notAvailable"] = true;
            return RedirectToAction("Index");
            
        }
    }
}

FcRoomBooking/Views/Shared/_AdministrationPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using FcRoomBooking.Areas.Identity.Data

@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService
@using FcRoomBooking.Constants

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@inject RoleManager<ApplicationRole> RoleManager


@*@if (SignInManager.IsSignedIn(User))
{
                    
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="form-elements">
                          <i class="icon-head menu-icon"></i>
                          <span class="menu-title">User Mangement</span>
                          @*<i class="menu-arrow"></i>
                          
                        </a>
       
            <div class="collapse" id="ui-basic">
                          <ul class="nav flex-column sub-menu">
                           <li class="nav-item"><a class="nav-link" asp-area="Identity" asp-page="/Account/Register">Set User</a></li>
                           <li class="nav-item"><a class="nav-link" asp-area="Identity" asp-controller="Administration" asp-action="CreateRole">Set Role</a></li>
                         </ul>
                    </div>
        

                        
                  </li>
}*@
@if (SignInManager.IsSignedIn(User))
{
    @if ((AuthorizationService.AuthorizeAsync(User, Permissions.User.View)).Result.Succeeded)
    {
        <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="form-elements">
                <i class="icon-head menu-icon"></i>
                <span class="menu-title">User Mangement</span>
                @*<i class="menu-arrow"></i>*@

            </a>

            <div class="collapse" id="ui-basic">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item"> <a class="nav-link" asp-controller="User" asp-action="Index">Users</a></li>
                    <li class="nav-item"><a class="nav-link" asp-controller="Role" asp-action="Index">Roles</a></li>


                </ul>
            </div>
        </li>
    }
}


   

FcRoomBooking/Views/Shared/_ChosenPartial.cshtml
<style>
    .chosen-container{
        display:flex;
    }

    .chosen-container-single .chosen-single{
        display:flex;
        width:100%;
        height:45px;
        border: 1px solid #ced4da;
        background: linear-gradient(#fff 100%,#f6f6f6 100%,#eee 52%,#f4f4f4 100%);
    }

    .chosen-container-single .chosen-single span {
            display: flex;
            width: 100%;
            align-items: center;
    }

    .chosen-container-single .chosen-single div{
            top:10px;
    }

    .chosen-container-multi .chosen-choices{
        display:flex;
        align-items:center;
        height:45px;
        border-radius:4px;
        background: linear-gradient(#fff 100%,#f6f6f6 100%,#eee 52%,#f4f4f4 100%);
    }
</style>
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/toast/jquery.toast.min.js"></script>
<script type="text/javascript" >
        $(document).ready(function () {
        $(".selectList").chosen(
            { 
                width: "100%",
            });
        });
</script>

FcRoomBooking/Views/Shared/_DeletePartialView.cshtml
@model FcRoomBooking.Models.ViewModel.RoleViewModel

@{
}
<div class="modal fade" id="RoleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Delete Role</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                        <h4>Do you want to delete this <span class="text-danger">@Model.Name</span>? </h4>
                  </div>
                  <div class="modal-footer">
                      <form method="post" asp-action="EditRole" asp-controller="Role">
                            <div class="input-group">
                                <input type="hidden"  asp-for="Id">
                                
                            </div>
                            <button type="submit" asp-controller="Role" asp-action="DeleteRole" asp-route-id="@Model.Id" class="btn btn-danger">Delete</button>
                        </form>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancle</button>
                  </div>
                </div>
              </div>
            </div>

FcRoomBooking/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FcRoomBooking</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FcRoomBooking.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Admin" asp-action="Index">FcRoomBooking</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    
                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - FcRoomBooking - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await RenderSectionAsync("Style", required: false)

</body>
</html>

FcRoomBooking/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Skydash Admin</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="~/vendors/mdi/css/materialdesignicons.min.css" />
    <link rel="stylesheet" href="~/Scripts/chosen/chosen.min.css"/>
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <link rel="stylesheet" href="~/admin_js/lib/main.css" />
    @*<link rel="stylesheet" href="~/vendors/datatables.net-bs4/dataTables.bootstrap4.css">
    <link rel="stylesheet" href="~/vendors/ti-icons/css/themify-icons.css">*@
    @*<link rel="stylesheet" type="text/css" href="~/admin_js/select.dataTables.min.css">*@
    <link rel="stylesheet" href="~/lib/toast/jquery.toast.min.css" />


    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="~/admin_css/vertical-layout-light/style.css">
    <!-- endinject -->
    <link rel="shortcut icon" href="~/images/favicon.png" />
    @*<link rel="stylesheet" href="~/css/toastinette.css">*@
</head>
<body>
    <div class="container-scroller">
        <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
            <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
                <a class="navbar-brand brand-logo mr-5" asp-controller="Admin" asp-action="Index"><img src="/images/logo.svg" class="mr-2" alt="logo" /></a>
                <a class="navbar-brand brand-logo-mini" asp-controller="Admin" asp-action="Index"><img src="/images/logo-mini.svg" alt="logo" /></a>
            </div>
            <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
                <ul class="navbar-nav mr-lg-2">
                    <li class="nav-item nav-search d-none d-lg-block">
                        <div class="input-group">
                            <div class="input-group-prepend hover-cursor" id="navbar-search-icon">
                                <span class="input-group-text" id="search">
                                    <i class="icon-search"></i>
                                </span>
                            </div>
                            <input type="text" class="form-control" id="navbar-search-input" placeholder="Search now" aria-label="search" aria-describedby="search">
                        </div>
                    </li>
                </ul>
                <ul class="navbar-nav navbar-nav-right">
                    <partial name="_NotificationPartial"/>
                    <partial name="_LoginPartialFirst" />
                </ul>
                <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
                    <span class="icon-menu"></span>
                </button>
            </div>
        </nav>
        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            <!-- partial:partials/_settings-panel.html -->
            <!-- partial -->
            <!-- partial:partials/_sidebar.html -->
            <nav class="sidebar sidebar-offcanvas" id="sidebar">
                <ul class="nav">
                    <li class="nav-item">
                        <a class="nav-link gap-2 d-flex" asp-controller="Admin" asp-action="Index">
                            <i class="mdi mdi-view-dashboard" style="font-size:large"></i>
                            <span class="menu-title ml-2">Dashboard</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link gap-2 d-flex" asp-controller="RoomBooking" asp-action="Index" asp-route-id="">
                            <i class="mdi mdi-book" style="font-size:large"></i>
                            <span class="menu-title ml-2">RoomBooking</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link gap-2 d-flex" asp-controller="MyBooking" asp-action="Index">
                            <i class="mdi mdi-book" style="font-size:large"></i>
                            <span class="menu-title ml-2">My Booking</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link gap-2 d-flex" asp-controller="Room" asp-action="List">
                            <i class="mdi mdi-view-dashboard" style="font-size:large"></i>
                            <span class="menu-title ml-2">Room</span>
                        </a>
                    </li>
                    <partial name="_AdministrationPartial" />
                </ul>
            </nav>
            <!-- partial -->
            <div class="main-panel">
                <div class="content-wrapper" style="padding:30px">
                    <div class="row">
                        @RenderBody()
                    </div>
                </div>
                <!-- content-wrapper ends -->
                <!-- partial:partials/_footer.html -->
                <footer class="footer">
                    <div class="d-sm-flex justify-content-center justify-content-sm-between">
                        <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2021.  Premium <a href="https://www.bootstrapdash.com/" target="_blank">Bootstrap admin template</a> from BootstrapDash. All rights reserved.</span>
                        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="ti-heart text-danger ml-1"></i></span>
                    </div>
                    <div class="d-sm-flex justify-content-center justify-content-sm-between">
                        <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Distributed by <a href="https://www.themewagon.com/" target="_blank">Themewagon</a></span>
                    </div>
                </footer>
                <!-- partial -->
            </div>
            <!-- main-panel ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="~/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/admin_js/dataTables.select.min.js"></script>

    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="~/admin_js/off-canvas.js"></script>
    <script src="~/admin_js/hoverable-collapse.js"></script>
    <script src="~/admin_js/template.js"></script>
    <script src="~/admin_js/settings.js"></script>
    <script src="~/admin_js/todolist.js"></script>
    <script src="~/admin_js/lib/main.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/vendors/mdi/css/materialdesignicons.min.css"></script>
    <script src="~/Scripts/chosen/chosen.jquery.min.js"></script>


    <!-- endinject -->
    <!-- Custom js for this page-->
    <script src="~/admin_js/file-upload.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await RenderSectionAsync("Style", required: false)
  

    @*<script src="~/admin_js/toastinette.js"></script>*@
    <!-- End custom js for this page-->
</body>

</html>

FcRoomBooking/Views/Shared/_LoginPartialFirst.cshtml
@using Microsoft.AspNetCore.Identity
@using FcRoomBooking.Areas.Identity.Data

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<ul class="navbar-nav">
@if (SignInManager.IsSignedIn(User))
    {
        var user = await UserManager.GetUserAsync(User);
        @if(user.ProfileImage != null)
        {
             var img = "data:image/*;base64," + Convert.ToBase64String(user.ProfileImage);
            <li class="nav-item nav-profile dropdown">
                <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown">
                  <img src="@img" alt="Image" alt="profile"/>
                </a>
           
              </li>
        }else
        {
               <li class="nav-item nav-profile dropdown">
                <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown">
                  <img src="https://cdn-icons-png.flaticon.com/512/456/456212.png">
                </a>
           
              </li>                     
        }
       
    <li class="nav-item">
        <a id="manage" class="nav-link text-dark" style="font-weight:bold;text-transform:uppercase" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">@user.Name</a>@*@UserManager.GetUserName(User)*@
    </li>
    <li class="nav-item">
        <form id="logoutForm" class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
            <button id="logout" type="submit" class="nav-link btn text-danger" style="font-weight:bold">Logout</button>
        </form>
    </li>
}
else
{
   @* <li class="nav-item">
        <a class="nav-link text-dark" id="register" asp-area="Identity" asp-page="/Account/Register">Register</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" id="login" asp-area="Identity" asp-page="/Account/Login">Login</a>
    </li>*@
}
</ul>

FcRoomBooking/Views/Shared/_NotificationPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using FcRoomBooking.Areas.Identity.Data
@using FcRoomBooking.Class

@inject UserManager<ApplicationUser> UserManager
@inject ApplicationDbContext dbcontext


@{
    Notification notification = new Notification(dbcontext,UserManager);
    var user = UserManager.GetUserId(User);
    var list = notification.Noti(user);
}
<li class="nav-item dropdown">
    <a class="nav-link count-indicator dropdown-toggle" id="notificationDropdown" href="#" data-toggle="dropdown">
        <span class="mdi mdi-bell" style="font-size:20px"></span>
        @if(list != null)
        {
            <span class="count"></span>
        }

    </a>
    <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="notificationDropdown">
        @if(list != null)
        {
            <p class="mb-0 font-weight-normal float-left dropdown-header">Notifications</p>

            @foreach (var item in list)
            {
            <a class="dropdown-item preview-item" asp-action="Index" asp-controller="RoomBooking" asp-route-id="@item.id">
                            <div class="preview-thumbnail">
                                <div class="preview-icon bg-info d-flex align-items-center">
                                    <span class="mdi mdi-email"></span>
                                </div>
                            </div>
                            <div class="preview-item-content">
                            <h6 class="preview-subject font-weight-normal">Meeting At <span class="text-success fw-bold">@item.bookingFrom</span></h6>
                                <p class="font-weight-light small-text mb-0 text-muted">
                                    Click for more info
                                </p>
                            </div>
                        </a>
            }
        }
        else
        {
            <p class="mb-0 font-weight-normal float-left dropdown-header">No Notifications</p>

        }

    </div>
</li>